#!/bin/bash
# Create minimal silent M4A files as placeholders
# These are very small base64-encoded silent audio files

# Minimal silent M4A (about 1 second of silence, ~200 bytes)
SILENT_M4A="AAAAIGZ0eXBNNEEgAAAAAE00QSBtcDQyaXNvbQAAAAhmcmVlAAAA3G1kYXQAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1vb3YAAABsbXZoZAAAAAAAAAAAAAAAAAAD6AAAACoAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAABx0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAACwAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAACQAAAEAAQAAAAA="

# Create all placeholder files
for file in soft_rain.m4a metal_scrape.m4a distant_piano.m4a alarm_beep.m4a ambient_drone.m4a; do
    echo "$SILENT_M4A" | base64 -d > "$file"
    echo "Created $file ($(stat -f%z "$file" 2>/dev/null || stat -c%s "$file") bytes)"
done
